### ISSUE TITLE
Looking to select a list of all entities from two entity caches using NgRx Data

### ISSUE THREAD

**Issue by ben-hastings** [satanTime/ngrx-entity-relationship#422]
Hi,

Awesome library! I am currently looking to use your library to select a list of all entities from two entity caches using NgRx Data.

Currently, I have something like:

```typescript
export const selectUser = rootEntity(
this.entityCache.users, // the selector of the user's feature.

 // now we define a relationship between a user and a company.
relatedEntity(
selectCompanyState, // a selector of the company's feature.
'companyId', // the key in the user's model that points to the company's id.
'company', // the key in the user's model that should be fulfilled with the company's entity.
),
);
```

I want to be able to do something like the below which will select all users and associated company.

```typescript
export const selectUsers = rootEntities(selectUser);
```

But it seems to be wanting an id or list of ids to filter by.

Is it possible with this library to return all?

**Comment by satanTime** [comment]
Hi @servelec-ben-hastings,

thanks for the question.

Your investigation is right. every selector requires a parameter which provides an id or an array of them.
The idea behind this is that a cache can contain a union of 2 lists.
For example, public projects and my projects. Both of them are cached under projects, but we wouldn't want to display someone's public project in my projects.

Nevertheless, it doesn't stop us from providing a selector of all ids, because root selectors accept as the parameter not only ids, but a selector which returns them.

Therefore we need a selector which gets all ids.
```ts
const allUserIds = createSelector(selectCompanyState, state => state.ids);
```

And later in code, we can select all users like that.
```ts
const allUsers$ = this.store.select(selectUsers, allUserIds);
```

Profit.


If you still want to have a single selector without using parameters, then you could follow this guide: https://ngrx-entity-relationship.sudo.eu/extra/usage-with-createselector, and do something like that:
```ts
export const selectAllUsers = createSelector(
  // selecting the whole store
  s => s,
  // selecting ids
  allUserIds,
  // selecting all users with desired relationships
  selectUsers,
);

store.select(selectAllUsers).subscribe(user => {
  // profit
});
```

I hope this helps, feel free to ask any further questions.

**Comment by ben-hastings** [comment]
That does, thanks a lot!
